/* Insert in include/config_directives.h; replace existing duplicates. */
CFGFUN(gradient_border_toggle, const char *value);
CFGFUN(gradient_border_color_start, const char *color);
CFGFUN(gradient_border_color_end, const char *color);
CFGFUN(gradient_border_inactive_start, const char *color);
CFGFUN(gradient_border_inactive_end, const char *color);
CFGFUN(gradient_border_direction, const char *direction);
CFGFUN(gradient_border_angle, const long angle);
CFGFUN(gradient_border_speed, const long speed);
CFGFUN(gradient_border_fps, const long fps);
CFGFUN(overview_live_previews, const char *value);
CFGFUN(overview_particles, const long count);
CFGFUN(overview_fps, const long fps);
CFGFUN(overview_border_color, const char *color);
CFGFUN(overview_border_color_end, const char *color);
CFGFUN(overview_border_inactive, const char *color);
CFGFUN(overview_border_width, const long width);
CFGFUN(overview_border_speed, const long speed);
CFGFUN(overview_wallpaper_path, char *wallpaper_path);
CFGFUN(overview_background_blur, const char *background_blur);
CFGFUN(dynamic_workspaces, const char *dynamic_workspaces);
CFGFUN(workspace_transition, const char *value);
CFGFUN(workspace_transition_duration, const long duration_ms);
CFGFUN(workspace_transition_direction, const char *direction);
CFGFUN(workspace_transition_fps, const long fps);
